language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  

install: 
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt-get install build-essential
  - sudo apt-get update
  - sudo apt-get install make

before_script:
  - mkdir build
  - cd build
  - cmake ..
script: 
  - make
  - touch test
  - echo -e "+ q 0 0 0 0\n ext\n" > test
  - ./oop_exercise_08 1 < test
  - rm -r test
  